# Generated by Django 3.1.3 on 2022-03-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qusetion',
            new_name='Question',
        ),
    ]
